language: node_js
node_js:
  - 6
  - 7
  - 8
  - node
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn add global ethereumjs-testrpc truffle
install:
  - yarn
script:
  - testrpc &
  - truffle test
